import localFont from "next/font/local";
import "./globals.css";

import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
