
import "./globals.css";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-outfit antialiased bg-putih`}
      >
        {children}
      </body>
    </html>
  );
}
